/* ═══════════════════════════════════════════════════════════════════
   BAZINO — data.js  (UI strings + curriculum-aligned question bank)
   Kaynak: KKTC MEKB müfredatı + 2026 Yerleştirme/KGS sınav kapsamı
   Soru formatı: r(bölge, lig 0/1/2, [konu:tr,en,fa], soru_tr, soru_en,
                soru_fa, seçenekler, doğru_index, açıklama_tr, en, fa)
   seçenekler: 4'lü dizi (ortak) veya {t,e,f} üç ayrı dizi olabilir.
   Ligler: 0=Gümüş(12-14)  1=Altın(14-16)  2=Elmas(16-18)
═══════════════════════════════════════════════════════════════════ */

const STR = {
tr:{
 tag:"Kıbrıs'ın dört bir yanında eğitici bir macera!",
 tip:"KKTC müfredatına uygun · 12–18 yaş · KGS/Yerleştirme hazırlık",
 name:"Adını yaz…", age:"Yaşını seç",
 gumus:"Gümüş Lig", altin:"Altın Lig", elmas:"Elmas Lig",
 leagueIs:"Ligin:", start:"Maceraya Başla!", cont:"Devam Et",
 mapT:"Kıbrıs Haritası — Bölgeni Seç", locked:"Seviye {n} gerekli",
 rounds:"{n} tur tamamlandı", startRtnr:"Bu bölgede maceraya başla!",
 bossN:"Sınav Salonu", bossD:"Gerçek sınav simülasyonu: 10 soru, 8 dakika, geçme barajı %60 — tıpkı Yerleştirme Sınavı!",
 bossLock:"4 bölgede tur bitir + Seviye 4 ol → Kilit açılır", best:"En iyi sonuç: %{n}",
 rDesc:"{n} soru · 3 can · Hatasız oyna, bonus kap!", go:"Başla!", back:"Haritaya Dön",
 qOf:"Soru {a}/{b}", correct:"Doğru! 🎉", wrong:"Yanlış!", why:"Açıklama", next:"Sonraki",
 dil:"🇬🇧 +%10 XP", dilOn:"İngilizce modu açık (+10%)",
 resW:"Tur Tamamlandı!", resL:"Canlar bitti — tekrar dene!", acc:"Doğruluk", xpg:"Kazanılan XP",
 cg:"Kazanılan Altın", newAch:"🏆 Yeni başarı: {n}!", lvlUp:"⬆️ Seviye atladın: Sv.{n}!",
 unlock:"🔓 Yeni bölge açıldı: {n}!", retry:"🔄 Tekrar Oyna", perfect:"Kusursuz tur! ✨",
 exT:"🎓 Sınav Salonu (Boss)", exP:"Yerleştirme Sınavı simülasyonu: iki oturumda toplam 10 soru, 8 dakika. Baraj: 6/10 (%60). Yanlışlar puanı geri götürmez — gerçek sınavdaki gibi!",
 exS1:"1. Oturum başlıyor", exS2:"2. Oturum", exBreak:"Oturum arası… hazır mısın?", exGo:"Sınava Gir",
 time:"Kalan süre", pass:"GEÇTİN! 🎓 Sınav şampiyonusun!", fail:"Barajın altında kaldın (%60 gerekli). Tekrar dene!",
 achT:"Başarılar", setT:"Ayarlar", lang:"Dil", sndOn:"Ses: Açık", sndOff:"Ses: Kapalı",
 reset:"Sıfırla", resetC:"Tüm ilerleme silinsin mi?", close:"Kapat", playA:"Tekrar Oyna",
 hint:"💡 İpucu: Matematik ve Fen sorularını İngilizce yanıtlamak +%10 XP kazandırır — gerçek sınavdaki dil katkı puanı gibi!",
 failNoHp:"3 hakkın bitti ama puanın yanmadı! 💪",
 good:"Harikasın!", lvl:"Seviye", toNext:"sonraki seviyeye {n} XP",
 need4:"Sınav Salonu için önce en az 4 bölgede 1'er tur bitirmelisin.",
 achFirst:"İlk Adım", achFirstD:"İlk doğru cevabını verdin!",
 achSeri:"Ateşli Seri", achSeriD:"Arka arkaya 5 doğru cevap!",
 achPerf:"Kusursuz", achPerfD:"Bir turu hiç can kaybetmeden bitirdin!",
 achDil:"Çift Dilli", achDilD:"İngilizce modunda 10 doğru cevap!",
 achFatih:"Bölge Fatihi", achFatihD:"Bir bölgede 3 tur tamamladın!",
 achSnav:"Sınav Şampiyonu", achSnavD:"Sınav Salonu'nu ≥%60 ile geçtin!",
 achSv5:"Yükselen Yıldız", achSv5D:"5. seviyeye ulaştın!",
 achGold:"Altın Avcısı", achGoldD:"Toplam 200 altın topladın!",
 done:"Aferin {n}!"
},
en:{
 tag:"An educational adventure across North Cyprus!",
 tip:"Aligned with TRNC curriculum · ages 12–18 · prep for KGS/Placement exams",
 name:"Enter your name…", age:"Pick your age",
 gumus:"Silver League", altin:"Gold League", elmas:"Diamond League",
 leagueIs:"Your league:", start:"Start the Adventure!", cont:"Continue",
 mapT:"Map of Cyprus — Pick a region", locked:"Requires level {n}",
 rounds:"{n} rounds completed", startRtnr:"Start in this region!",
 bossN:"Exam Hall", bossD:"Real exam simulation: 10 questions, 8 minutes, pass mark 60% — just like the Placement Exam!",
 bossLock:"Finish a round in 4 regions + reach level 4 to unlock", best:"Best score: {n}%",
 rDesc:"{n} questions · 3 lives · Play flawlessly for bonuses!", go:"Go!", back:"Back to Map",
 qOf:"Question {a}/{b}", correct:"Correct! 🎉", wrong:"Wrong!", why:"Explanation", next:"Next",
 dil:"🇬🇧 +10% XP", dilOn:"English mode on (+10%)",
 resW:"Round Complete!", resL:"Out of lives — try again!", acc:"Accuracy", xpg:"XP earned",
 cg:"Coins earned", newAch:"🏆 New achievement: {n}!", lvlUp:"⬆️ Level up: Lv.{n}!",
 unlock:"🔓 New region unlocked: {n}!", retry:"🔄 Play Again", perfect:"Flawless round! ✨",
 exT:"🎓 Exam Hall (Boss)", exP:"Placement Exam simulation: 10 questions in two sittings, 8 minutes. Pass mark: 6/10 (60%). Wrong answers never subtract points — just like the real exam!",
 exS1:"Sitting 1 begins", exS2:"Sitting 2", exBreak:"Break between sittings… ready?", exGo:"Enter Exam",
 time:"Time left", pass:"PASSED! 🎓 You are an exam champion!", fail:"Below the 60% pass mark. Try again!",
 achT:"Achievements", setT:"Settings", lang:"Language", sndOn:"Sound: On", sndOff:"Sound: Off",
 reset:"Reset", resetC:"Delete all progress?", close:"Close", playA:"Play Again",
 hint:"💡 Tip: answering Math & Science questions in English earns +10% XP — like the bonus language point of the real exam!",
 failNoHp:"3 lives gone, but your points are safe! 💪",
 good:"Great job!", lvl:"Level", toNext:"{n} XP to next level",
 need4:"To enter the Exam Hall, first complete one round in at least 4 regions.",
 achFirst:"First Step", achFirstD:"You gave your first correct answer!",
 achSeri:"Hot Streak", achSeriD:"5 correct answers in a row!",
 achPerf:"Flawless", achPerfD:"You finished a round with all lives!",
 achDil:"Bilingual", achDilD:"10 correct answers in English mode!",
 achFatih:"Conqueror", achFatihD:"You completed 3 rounds in one region!",
 achSnav:"Exam Champion", achSnavD:"You passed the Exam Hall at 60%+!",
 achSv5:"Rising Star", achSv5D:"You reached level 5!",
 achGold:"Gold Hunter", achGoldD:"You collected 200 coins in total!",
 done:"Well done {n}!"
},
fa:{
 tag:"ماجراجویی آموزشی در سراسر قبرس شمالی!",
 tip:"هم‌راستا با سرفصل‌های KKTC · سنین ۱۲ تا ۱۸ · آماده‌سازی آزمون‌های KGS و Yerleştirme",
 name:"نامت را بنویس…", age:"سنت را انتخاب کن",
 gumus:"لیگ نقره", altin:"لیگ طلا", elmas:"لیگ الماس",
 leagueIs:"لیگ تو:", start:"شروع ماجرا!", cont:"ادامه",
 mapT:"نقشه قبرس — منطقه‌ات را انتخاب کن", locked:"نیازمند سطح {n}",
 rounds:"{n} دور کامل شده", startRtnr:"شروع ماجراجویی در این منطقه!",
 bossN:"سالن امتحان", bossD:"شبیه‌سازی آزمون واقعی: ۱۰ سؤال، ۸ دقیقه، حدنصاب قبولی ۶۰٪ — درست مثل آزمون Yerleştirme!",
 bossLock:"در ۴ منطقه یک دور کامل کن + به سطح ۴ برس تا باز شود", best:"بهترین نتیجه: {n}٪",
 rDesc:"{n} سؤال · ۳ قلب · بدون خطا بازی کن و جایزه بگیر!", go:"بزن بریم!", back:"بازگشت به نقشه",
 qOf:"سؤال {a} از {b}", correct:"درست! 🎉", wrong:"اشتباه!", why:"توضیح", next:"بعدی",
 dil:"🇬🇧 ‏+۱۰٪ امتیاز", dilOn:"حالت انگلیسی فعال +۱۰٪",
 resW:"دور کامل شد!", resL:"قلب‌ها تمام شد — دوباره تلاش کن!", acc:"دقت", xpg:"امتیاز کسب‌شده",
 cg:"سکه کسب‌شده", newAch:"🏆 دست‌آورد جدید: {n}!", lvlUp:"⬆️ سطحت بالا رفت: {n}!",
 unlock:"🔓 منطقه جدید باز شد: {n}!", retry:"🔄 دوباره بازی کن", perfect:"دور بدون خطا! ✨",
 exT:"🎓 سالن امتحان (باس)", exP:"شبیه‌سازی آزمون پذیرش: ۱۰ سؤال در دو سانس، ۸ دقیقه. حدنصاب: ۶ از ۱۰ (۶۰٪). پاسخ غلط امتیازت را کم نمی‌کند — مثل آزمون واقعی!",
 exS1:"سانس اول شروع شد", exS2:"سانس دوم", exBreak:"وقفه بین دو سانس… آماده‌ای؟", exGo:"ورود به امتحان",
 time:"زمان باقیمانده", pass:"قبول شدی! 🎓 قهرمان امتحان هستی!", fail:"زیر حدنصاب ۶۰٪ ماندی. دوباره تلاش کن!",
 achT:"دست‌آوردها", setT:"تنظیمات", lang:"زبان", sndOn:"صدا: روشن", sndOff:"صدا: خاموش",
 reset:"بازنشانی", resetC:"همه پیشرفت‌ها پاک شود؟", close:"بستن", playA:"بازی دوباره",
 hint:"💡 نکته: پاسخ دادن به سؤالات ریاضی و علوم به انگلیسی ۱۰٪ امتیاز بیشتر می‌دهد — مثل امتیاز تشویقی زبان در آزمون واقعی!",
 failNoHp:"۳ جان رفت، اما امتیازت سوخته نشد! 💪",
 good:"آفرین!", lvl:"سطح", toNext:"{n} امتیاز تا سطح بعد",
 need4:"برای ورود به سالن امتحان، ابتدا در دست‌کم ۴ منطقه یک دور کامل کن.",
 achFirst:"گام اول", achFirstD:"اولین پاسخ درستت را دادی!",
 achSeri:"حرارت مسلسل", achSeriD:"۵ پاسخ درست پشت سر هم!",
 achPerf:"بی‌نقص", achPerfD:"یک دور را با همه قلب‌ها تمام کردی!",
 achDil:"دوزبانه", achDilD:"۱۰ پاسخ درست در حالت انگلیسی!",
 achFatih:"فاتح منطقه", achFatihD:"۳ دور در یک منطقه کامل کردی!",
 achSnav:"قهرمان امتحان", achSnavD:"سالن امتحان را با ۶۰٪+ گذراندی!",
 achSv5:"ستاره در حال طلوع", achSv5D:"به سطح ۵ رسیدی!",
 achGold:"شکارچی طلا", achGoldD:"در مجموع ۲۰۰ سکه جمع کردی!",
 done:"آفرین {n}!"
}};

/* ── لیگ‌ها ── */
const LEAGUES=[
 {id:"gumus", emoji:"🥈", min:12, max:14},
 {id:"altin", emoji:"🥇", min:15, max:16},
 {id:"elmas", emoji:"💎", min:17, max:18}
];

/* ── مناطق نقشه ── */
const REGIONS=[
 {id:"math",   cls:"c-math",   emoji:"🧮", needLevel:1, city:{tr:"Güzelyurt",  en:"Güzelyurt",  fa:"گوزل‌یورت"},
   name:{tr:"Matematik Vadisi",en:"Math Valley",fa:"دره ریاضی"}},
 {id:"science",cls:"c-science",emoji:"🔬", needLevel:1, city:{tr:"Gazimağusa", en:"Famagusta",  fa:"غازی‌مغوسا"},
   name:{tr:"Fen Kalesi",     en:"Science Castle",fa:"قلعه علوم"}},
 {id:"english",cls:"c-english",emoji:"🇬🇧", needLevel:1, city:{tr:"Girne",      en:"Kyrenia",    fa:"گیرنه"},
   name:{tr:"Dil Limanı",     en:"Language Harbor",fa:"بندر زبان"}},
 {id:"history",cls:"c-history",emoji:"🏛️", needLevel:3, city:{tr:"Lefkoşa",    en:"Nicosia",    fa:"لفکوشا"},
   name:{tr:"Tarih Surları",  en:"History Walls",fa:"دیوارهای تاریخ"}},
 {id:"geo",    cls:"c-geo",    emoji:"🗺️", needLevel:3, city:{tr:"İskele",     en:"İskele",     fa:"اسکله"},
   name:{tr:"Doğa Sahili",    en:"Nature Coast",fa:"ساحل طبیعت"}},
 {id:"zeka",   cls:"c-zeka",   emoji:"🧩", needLevel:5, city:{tr:"Lefke",       en:"Lefke",      fa:"لفکه"},
   name:{tr:"Zekâ Şehri",     en:"Puzzle City",fa:"شهر ذکا"}}
];

/* ── دست‌آوردها ── */
const ACH=[
 {id:"first", emoji:"🌱", name:{tr:"achFirst", en:"achFirst", fa:"achFirst"}, desc:{tr:"achFirstD",en:"achFirstD",fa:"achFirstD"}},
 {id:"seri",  emoji:"🔥", name:{tr:"achSeri",  en:"achSeri",  fa:"achSeri"},  desc:{tr:"achSeriD", en:"achSeriD", fa:"achSeriD"}},
 {id:"perf",  emoji:"✨", name:{tr:"achPerf",  en:"achPerf",  fa:"achPerf"},  desc:{tr:"achPerfD", en:"achPerfD", fa:"achPerfD"}},
 {id:"dil",   emoji:"🇬🇧",name:{tr:"achDil",   en:"achDil",   fa:"achDil"},   desc:{tr:"achDilD",  en:"achDilD",  fa:"achDilD"}},
 {id:"fatih", emoji:"🚩", name:{tr:"achFatih", en:"achFatih", fa:"achFatih"}, desc:{tr:"achFatihD",en:"achFatihD",fa:"achFatihD"}},
 {id:"snav",  emoji:"🎓", name:{tr:"achSnav",  en:"achSnav",  fa:"achSnav"},  desc:{tr:"achSnavD", en:"achSnavD", fa:"achSnavD"}},
 {id:"sv5",   emoji:"⭐", name:{tr:"achSv5",   en:"achSv5",   fa:"achSv5"},   desc:{tr:"achSv5D",  en:"achSv5D",  fa:"achSv5D"}},
 {id:"gold",  emoji:"🪙", name:{tr:"achGold",  en:"achGold",  fa:"achGold"},  desc:{tr:"achGoldD", en:"achGoldD", fa:"achGoldD"}}
];

/* ── سطح‌بندی XP ── */
const LEVEL_XP=[0,100,250,500,800,1200,1800,2500,3500,4500];

/* ═════════ بانک سؤالات (برگرفته از سرفصل‌های رسمی — research/ سندهای ۰۲ تا ۰۴) ═════════
   r(bölge,lig,konu,soruTR,soruEN,soruFA, seçenek…, doğruİndeks, açıkTR, açıkEN, açıkFA)
   seçenek: tek ortak dizi  YA DA  {t:[…],e:[…],f:[…]}  YA DA  üç ayrı dizi */
function r(region,lev,topic,qt,qe,qf){
  var a=[].slice.call(arguments,6);
  var wf=a.pop(), we=a.pop(), wt=a.pop();
  var ans=0, list=[];
  for(var i=0;i<a.length;i++){
    if(typeof a[i]==="number") ans=a[i]; else list.push(a[i]);
  }
  var o;
  if(list.length===1 && Array.isArray(list[0])) o={t:list[0],e:list[0],f:list[0]};
  else if(list.length===1) o=list[0]; /* {t,e,f} objesi */
  else o={t:list[0],e:list[1],f:list[2]};
  return {region:region,lev:lev,topic:topic,qt:qt,qe:qe,qf:qf,o:o,ans:ans,wt:wt,we:we,wf:wf};
}

const Q=[
/* ── 🧮 math · Gümüş (پایه ۸ KKTC: Sayılar/Cebir/Geometri) ── */
r("math",0,["Çarpanlar-Katlar","Factors-Multiples","مضرب‌ها"],
"12 sayısının çarpanlarından (bölenlerinden) biri OLMAYAN sayı hangisidir?",
"Which number is NOT a factor of 12?",
"کدام عدد مضرب ۱۲ نیست؟",
["3","4","5","6"],2,
"12'nin çarpanları 1, 2, 3, 4, 6 ve 12'dir. 5, bunlardan değildir.",
"The factors of 12 are 1, 2, 3, 4, 6 and 12. 5 is not among them.",
"مضرب‌های ۱۲ عبارت‌اند از ۱،۲،۳،۴،۶،۱۲. عدد ۵ در میانشان نیست."),
r("math",0,["Üslü İfadeler","Exponents","توان"],
"2³ × 2² işleminin sonucu kaçtır?","What is 2³ × 2²?","حاصل عبارت 2³ × 2² کدام است؟",
["10","16","32","64"],2,
"Taban aynı ise üsler toplanır: 2³⁺² = 2⁵ = 32",
"When the base is the same, add the exponents: 2⁵ = 32",
"وقتی پایه‌ها یکی‌اند توان‌ها جمع می‌شوند: ۳۲ = 2⁵"),
r("math",0,["Kareköklü Sayılar","Square Roots","رادیکال"],
"√144 kaçtır?","What is √144?","‏√۱۴۴ چند است؟",
["72","12","14","24"],1,
"12 × 12 = 144, o yüzden √144 = 12","Since 12 × 12 = 144, √144 = 12","چون ۱۴۴ = ۱۲ × ۱۲ است، جواب ۱۲ است."),
r("math",0,["Özdeşlikler","Identities","اتحادها"],
"(x + 3)² özdeşliğinin açılımı hangisidir?","What is the expansion of (x + 3)²?","بسط (x + 3)² کدام است؟",
["x² + 6x + 9","x² + 9","x² + 3x + 9","x² + 5x + 6"],0,
"Tam kare: a² + 2ab + b² → x² + 2·x·3 + 9 = x² + 6x + 9",
"Perfect square: a² + 2ab + b² → x² + 6x + 9",
"مربع کامل: a² + 2ab + b² ← x² + 6x + 9"),
r("math",0,["Doğrusal Denklemler","Linear Equations","معادله خطی"],
"3x − 7 = 11 denkleminde x kaçtır?","If 3x − 7 = 11, what is x?","اگر 3x − 7 = 11 باشد، x چند است؟",
["5","6","7","8"],1,
"3x = 11 + 7 = 18 → x = 18 ÷ 3 = 6","3x = 18, so x = 6","‏۳x = ۱۸ پس x = ۶"),
/* ── math · Altın (Lise 9: Mantık, Kümeler, Fonksiyon…) ── */
r("math",1,["Kümeler","Sets","مجموعه‌ها"],
"A = {1,2,3,4,5} ve B = {3,4,5,6} ise A ∩ B kümesi hangisidir?",
"A = {1,2,3,4,5}, B = {3,4,5,6}. What is A ∩ B?",
"اگر A = {1,2,3,4,5} و B = {3,4,5,6} باشد، اشتراک A ∩ B کدام است؟",
["{3, 4, 5}","{2, 3, 4}","{1,2,3,4,5,6}","{3, 4}"],0,
"Kesişim her iki kümede de bulunan elemanlardır: 3, 4, 5",
"Intersection = elements in both sets: 3, 4, 5",
"اشتراک یعنی اعضایی که در هر دو مجموعه هستند: ۳،۴،۵"),
r("math",1,["Mantık","Logic","منطق"],
"'p ∧ ¬p' (p ve değili) bileşik önermesi her zaman nedir?",
"The compound statement 'p AND NOT-p' is always…?",
"گزاره مرکب «p ∧ ¬p» همیشه چیست؟",
["Her zaman yanlış","Her zaman doğru","p'ye bağlı","Belirsiz"],
["Always false","Always true","Depends on p","Undefined"],
["همیشه نادرست","همیشه درست","بستگی به p دارد","نامشخص"],0,
"Bir önerme ve değili aynı anda doğru olamaz — çelişki!",
"A statement and its negation cannot both be true — contradiction!",
"یک گزاره و نقیضش نمی‌توانند هم‌زمان درست باشند — تناقض!"),
r("math",1,["Fonksiyonlar","Functions","توابع"],
"f(x) = 2x + 1 fonksiyonunda f(3) kaçtır?","If f(x) = 2x + 1, what is f(3)?","در تابع f(x) = 2x + 1، مقدار f(3) چند است؟",
["6","7","8","9"],1,
"f(3) = 2×3 + 1 = 7","f(3) = 2×3 + 1 = 7","‏f(3) = 2×3 + 1 = 7"),
r("math",1,["Trigonometri","Trigonometry","مثلثات"],
"sin 30° kaçtır?","What is sin 30°?","مقدار sin 30° چقدر است؟",
["1/2","√2/2","√3/2","1"],0,
"30°-60°-90° dik üçgeninde sin 30° = 1/2","In the 30-60-90 triangle, sin 30° = 1/2","در مثلث ۳۰-۶۰-۹۰، sin 30° برابر ۱/۲ است."),
r("math",1,["İstatistik","Statistics","آمار"],
"4, 6, 8, 10 sayılarının aritmetik ortalaması kaçtır?",
"What is the mean of 4, 6, 8 and 10?","میانگین اعداد ۴،۶،۸،۱۰ چند است؟",
["6","7","8","7.5"],1,
"(4+6+8+10) ÷ 4 = 28 ÷ 4 = 7","(4+6+8+10) ÷ 4 = 7","‏(۴+۶+۸+۱۰) ÷ ۴ = ۷"),
/* ── math · Elmas (A-Level/YKS kavramları) ── */
r("math",2,["Türev","Differentiation","مشتق"],
"y = x³ fonksiyonunun türevi nedir?","What is the derivative of y = x³?","مشتق تابع y = x³ چیست؟",
["3x²","x²","3x","2x³"],0,
"Üslü kural: (xⁿ)' = n·xⁿ⁻¹ → 3x²","Power rule: (xⁿ)' = n·xⁿ⁻¹ → 3x²","قاعده توان: (xⁿ)′ = n·xⁿ⁻¹ ← 3x²"),
r("math",2,["Limit","Limits","حد"],
"lim (x→2) (x² − 4)/(x − 2) değeri kaçtır?","Evaluate lim (x→2) (x² − 4)/(x − 2).","مقدار lim(x→2) (x² − 4)/(x − 2) کدام است؟",
["2","4","0","Tanımsız / Undefined / تعریف‌نشده"],1,
"(x²−4) = (x−2)(x+2); sadeleşince x+2 → 4","(x²−4)=(x−2)(x+2); simplify to x+2 → 4","‏(x²−4)=(x−2)(x+2) و پس از ساده‌سازی x+2 ← ۴"),
r("math",2,["Logaritma","Logarithms","لگاریتم"],
"log₂ 8 kaçtır?","What is log₂ 8?","مقدار log₂ 8 چند است؟",
["2","3","4","6"],1,
"2³ = 8 olduğundan log₂ 8 = 3","Because 2³ = 8, the answer is 3","چون 8 = 2³ است، جواب ۳ است."),
r("math",2,["Kombinasyon","Combinations","ترکیب"],
"5 kişi arasından 2 kişilik ekip kaç farklı şekilde seçilir? C(5,2)",
"In how many ways can a team of 2 be chosen from 5 people? C(5,2)",
"از میان ۵ نفر، یک تیم ۲ نفره به چند طریق می‌توان انتخاب کرد؟ C(5,2)",
["10","20","7","25"],0,
"C(5,2) = 5!/(2!·3!) = 20/2 = 10","C(5,2) = 5!/(2!·3!) = 10","‏C(5,2) = 5!/(2!·3!) = 10"),
r("math",2,["Bileşke Fonksiyon","Composite Functions","تابع مرکب"],
"f(x)=x+1 ve g(x)=2x ise f(g(3)) kaçtır?",
"With f(x)=x+1 and g(x)=2x, what is f(g(3))?","اگر f(x)=x+1 و g(x)=2x باشد، f(g(3)) چند است؟",
["6","7","8","9"],1,
"g(3)=6; sonra f(6)=6+1=7","g(3)=6, then f(6)=7","‏g(3)=6 و سپس f(6)=7"),

/* ── 🔬 science · Gümüş (Fen ve Teknoloji 8 — 8 resmi ünite) ── */
r("science",0,["Canlılar ve Enerji","Organisms & Energy","جانداران و انرژی"],
"Fotosentez sırasında bitkiler atmosferden hangi gazı alır?",
"Which gas do plants take from the air during photosynthesis?",
"گیاهان در فتوسنتز کدام گاز را از هوا می‌گیرند؟",
["Oksijen (O₂)","Karbondioksit (CO₂)","Azot (N₂)","Hidrojen (H₂)"],
["Oxygen (O₂)","Carbon dioxide (CO₂)","Nitrogen (N₂)","Hydrogen (H₂)"],
["اکسیژن (O₂)","دی‌اکسید کربن (CO₂)","نیتروژن (N₂)","هیدروژن (H₂)"],1,
"Fotosentez: CO₂ + su + ışık → besin + O₂. Bitki CO₂ alır, O₂ verir.",
"Photosynthesis: CO₂ + water + light → food + O₂. Plants absorb CO₂.",
"فتوسنتز: CO₂ + آب + نور ← غذا + O₂. گیاه CO₂ می‌گیرد."),
r("science",0,["Basit Makineler","Simple Machines","ماشین‌های ساده"],
"Destek noktası yük ile kuvvetin arasında olan kaldıraç örneği hangisidir?",
"Which lever has the fulcrum between the load and the effort?",
"کدام اهرم تکیه‌گاه بین بار و نیرو دارد؟",
["El arabası (yük ortada)","Tahterevalli","Ceviz kıracağı","Cımbız (kuvvet ortada)"],
["Wheelbarrow (load in middle)","Seesaw","Nutcracker","Tweezers (effort in middle)"],
["فرغون (بار در میانه)","الاکلنگ","گردوشکن","موچین (نیرو در میانه)"],1,
"Tahterevallide destek tam ortadadır; el arabasında yük, cımbızda kuvvet ortadadır.",
"In a seesaw the fulcrum is in the middle; load is central in a wheelbarrow, effort in tweezers.",
"در الاکلنگ تکیه‌گاه درست وسط است؛ در فرغون بار و در موچین نیرو وسط است."),
r("science",0,["Maddenin Yapısı","Structure of Matter","ساختار ماده"],
"Atomun çekirdeğinde bulunan (+) pozitif yüklü tanecik hangisidir?",
"Which particle in the nucleus of an atom has a positive (+) charge?",
"کدام ذره در هسته اتم بار مثبت دارد؟",
["Elektron","Nötron","Proton","İyon"],
["Electron","Neutron","Proton","Ion"],
["الکترون","نوترون","پروتون","یون"],2,
"Çekirdekte proton (+) ve nötron (yüksüz) bulunur; elektron (−) yörüngededir.",
"The nucleus holds protons (+) and neutrons; electrons (−) orbit around it.",
"در هسته پروتون (+) و نوترون (خنثی) است؛ الکترون (−) در مدار است."),
r("science",0,["Hücre Bölünmesi","Cell Division","تقسیم سلولی"],
"Mitoz bölünme sonucunda bir hücreden kaç özdeş hücre oluşur?",
"How many identical cells result from one cell after mitosis?",
"از تقسیم میتوز یک سلول، چند سلول همسان ساخته می‌شود؟",
["1","2","3","4"],1,
"Mitoz = büyüme ve onarım için 2 özdeş yavru hücre (2n → 2n).",
"Mitosis gives 2 identical daughter cells (2n → 2n) for growth/repair.",
"میتوز ۲ سلول دختر همسان می‌سازد (2n → 2n)."),
r("science",0,["Yeryüzü ve Hava","Earth & Weather","زمین و هوا"],
"Alçak basınç alanlarında genellikle nasıl bir hava görülür?",
"What weather is typical over a low-pressure area?",
"در نواحی کم‌فشار معمولاً چه هوایی دیده می‌شود؟",
["Açık ve güneşli","Kapalı ve yağışlı","Rüzgârsız ve kuru","Don olayı"],
["Clear and sunny","Cloudy and rainy","Windless and dry","Frost"],
["صاف و آفتابی","ابری و بارانی","بی‌باد و خشک","یخبندان"],1,
"Alçak basınçta hava yükselir → bulut ve yağış oluşur.",
"In low pressure air rises → clouds and rain form.",
"در کم‌فشار هوا بالا می‌رود و ابر و باران ساخته می‌شود."),
/* ── science · Altın (Fizik/Kimya/Biyoloji 9-10) ── */
r("science",1,["Fizik • Hareket","Physics • Motion","فیزیک • حرکت"],
"Newton'un 2. yasası F = m × a hangi büyüklükleri ilişkilendirir?",
"Newton's 2nd law F = m × a relates which quantities?",
"قانون دوم نیوتن F = m × a چه کمیت‌هایی را پیوند می‌دهد؟",
["Kuvvet • kütle • ivme","Hız • zaman • yol","Enerji • güç • ısı","Basınç • hacim • sıcaklık"],
["Force • mass • acceleration","Speed • time • distance","Energy • power • heat","Pressure • volume • temperature"],
["نیرو • جرم • شتاب","سرعت • زمان • مسیر","انرژی • توان • گرما","فشار • حجم • دما"],0,
"Net kuvvet = kütle × ivmedir; birim newton (N).",
"Net force = mass × acceleration; the unit is newton (N).",
"نیروی خالص = جرم × شتاب؛ یکا نیوتن (N) است."),
r("science",1,["Kimya • Mol","Chemistry • Mole","شیمی • مول"],
"1 mol maddede yaklaşık kaç tanecik vardır?",
"Approximately how many particles are in one mole?",
"در یک مول ماده تقریباً چند ذره وجود دارد؟",
["6,02 × 10²³","3 × 10⁸","1,6 × 10⁻¹⁹","10²"],0,
"Avogadro sayısı: 6,02 × 10²³ tanecik/mol.",
"Avogadro's number: 6.02 × 10²³ particles per mole.",
"عدد آووگادرو: 6,02 × 10²³ ذره در هر مول."),
r("science",1,["Biyoloji • Hücre","Biology • Cell","زیست • سلول"],
"Hücrede enerji (ATP) üreten organel hangisidir?",
"Which organelle produces energy (ATP) in the cell?",
"کدام اندامک در سلول انرژی (ATP) تولید می‌کند؟",
["Ribozom","Kloroplast","Mitokondri","Çekirdek"],
["Ribosome","Chloroplast","Mitochondrion","Nucleus"],
["ریبزوم","کلروپلاست","میتوکندری","هسته"],2,
"Mitokondri, hücresel solunumla ATP üretir — 'hücrenin enerji santrali'.",
"The mitochondrion makes ATP in cellular respiration — the powerhouse of the cell.",
"میتوکندری با تنفس سلولی ATP می‌سازد — نیروگاه سلول."),
r("science",1,["Kimya • Asit-Baz","Chemistry • Acids","شیمی • اسید و باز"],
"pH değeri 3 olan bir çözelti nasıldır?","How would you describe a solution with pH 3?","محلولی با pH برابر ۳ چه‌گونه است؟",
["Nötr","Asidik","Bazik","Tuzlu"],
["Neutral","Acidic","Basic","Salty"],
["خنثی","اسیدی","بازی","شور"],1,
"pH < 7 asidik, pH = 7 nötr, pH > 7 baziktir.",
"pH below 7 is acidic, 7 is neutral, above 7 is basic.",
"‏pH کمتر از ۷ اسیدی، ۷ خنثی و بیشتر از ۷ بازی است."),
r("science",1,["Fizik • Hız","Physics • Speed","فیزیک • سرعت"],
"2 saatte 100 km yol alan aracın ortalama hızı kaç km/h'dir?",
"A car covers 100 km in 2 hours. What is its average speed?",
"خودرویی در ۲ ساعت ۱۰۰ کیلومتر می‌رود؛ سرعت متوسطش چقدر است؟",
["25","50","60","200"],1,
"Hız = yol ÷ zaman = 100 ÷ 2 = 50 km/h","Speed = distance ÷ time = 50 km/h","سرعت = مسیر ÷ زمان = ۱۰۰ ÷ ۲ = ۵۰"),
/* ── science · Elmas (A-Level) ── */
r("science",2,["Fizik • Elektrik","Physics • Electricity","فیزیک • الکتریسیته"],
"V = I × R formülünde 12 V ve 4 Ω için akım kaç amperdir?",
"Using V = I × R with 12 V and 4 Ω, what current flows?","طبق V = I × R با ۱۲ ولت و ۴ اهم، جریان چند آمپر است؟",
["2 A","3 A","6 A","48 A"],1,
"I = V ÷ R = 12 ÷ 4 = 3 A","I = V ÷ R = 3 A","‏I = V ÷ R = 12 ÷ 4 = 3"),
r("science",2,["Biyoloji • Genetik","Biology • Genetics","زیست • ژنتیک"],
"Mendel'e göre Aa × Aa çaprazlamasında baskın fenotip oranı kaçtır?",
"In Mendel's Aa × Aa cross, what fraction shows the dominant trait?",
"در تلاقی Aa × Aa مندل، چه کسری صفت غالب را نشان می‌دهد؟",
["1/2","2/3","3/4","4/4"],2,
"AA, Aa, Aa, aa → dörtte üçü baskın özelliği gösterir.",
"AA, Aa, Aa, aa → three quarters show the dominant trait.",
"‏AA، Aa، Aa، aa ← سه‌چهارم صفت غالب دارند."),
r("science",2,["Kimya • Organik","Chemistry • Organic","شیمی • آلی"],
"Doğal gazın ana bileşeni olan en basit organik bileşik hangisidir?",
"What is the simplest organic compound, the main part of natural gas?",
"ساده‌ترین ترکیب آلی و جزء اصلی گاز طبیعی کدام است؟",
["Etan (C₂H₆)","Metan (CH₄)","Propan (C₃H₈)","Bütan (C₄H₁₀)"],
["Ethane (C₂H₆)","Methane (CH₄)","Propane (C₃H₈)","Butane (C₄H₁₀)"],
["اتان (C₂H₆)","متان (CH₄)","پروپان (C₃H₈)","بوتان (C₄H₁₀)"],1,
"Metan: 1 karbon + 4 hidrojen; en basit alkandır.",
"Methane: 1 carbon + 4 hydrogens — the simplest alkane.",
"متان: یک کربن + چهار هیدروژن؛ ساده‌ترین آلکان."),
r("science",2,["Biyoloji • DNA","Biology • DNA","زیست • DNA"],
"DNA'da adenin (A) bazı hangi bazla eşleşir?","In DNA, which base pairs with adenine (A)?","در DNA باز آدنین با کدام باز جفت می‌شود؟",
["Guanin (G)","Sitozin (C)","Timin (T)","Urasil (U)"],
["Guanine (G)","Cytosine (C)","Thymine (T)","Uracil (U)"],
["گوانین (G)","سیتوزین (C)","تیمین (T)","یوراسیل (U)"],2,
"DNA'da A–T ve G–C eşleşir (U, yalnızca RNA'dadır).",
"In DNA, A pairs with T and G with C (U is only in RNA).",
"در DNA، A با T و G با C جفت می‌شود (U فقط در RNA است)."),
r("science",2,["Fizik • Dalgalar","Physics • Waves","فیزیک • موج"],
"Frekansı 5 Hz, dalga boyu 2 m olan dalganın hızı kaç m/s'dir?",
"A wave has frequency 5 Hz and wavelength 2 m. What is its speed?",
"موجی با بسامد ۵ هرتز و طول‌موج ۲ متر؛ سرعتش چقدر است؟",
["2,5","7","10","0,4"],2,
"v = f × λ = 5 × 2 = 10 m/s","v = f × λ = 10 m/s","‏v = f × λ = ۵ × ۲ = ۱۰"),

/* ── 🇬🇧 english · Gümüş (resmi 8. sınıf listesi) ── */
r("english",0,["Past Simple","Past Simple","گذشته ساده"],
"She ___ to school by bus yesterday.","She ___ to school by bus yesterday.","دیروز او با اتوبوس به مدرسه ___: She ___ to school by bus yesterday.",
["goes","went","going","go"],1,
"'Yesterday' → Past Simple: go → went (düzensiz fiil).",
"'Yesterday' needs the Past Simple: go → went (irregular).",
"کلمه yesterday یعنی گذشته ساده: went ← go"),
r("english",0,["Comparatives","Comparatives","مقایسه‌ای"],
"Mountains are ___ than hills.","Mountains are ___ than hills.","کوه‌ها از تپه‌ها ___ اند: Mountains are ___ than hills.",
["high","higher","highest","more high"],1,
"Kısa sıfatlarda karşılaştırma: -er + than → higher.",
"Short adjectives take -er + than → higher.",
"صفت‌های کوتاه با -er مقایسه می‌شوند: higher"),
r("english",0,["Quantifiers","Quantifiers","تعیین‌گرها"],
"There isn't ___ milk in the fridge.","There isn't ___ milk in the fridge.","در یخچال هیچ شیر نیست: There isn't ___ milk in the fridge.",
["some","a","any","many"],2,
"Olumsuz cümlelerde 'any' kullanılır; 'some' olumlularda.",
"Negative sentences take 'any'; 'some' is for affirmatives.",
"در جمله منفی any و در مثبت some می‌آید."),
r("english",0,["Necessity: have to","have to","الزام"],
"Students ___ wear uniforms at our school. (kural / a rule)",
"Students ___ wear uniforms at our school. (a rule)",
"دانش‌آموزان موظف‌اند یونیفرم بپوشند: Students ___ wear uniforms.",
["have to","can","might","would"],0,
"Zorunluluk bildiren kurallar için 'have/has to' kullanılır.",
"Use 'have/has to' for rules and necessity.",
"برای قواعد و الزام از have to استفاده می‌کنیم."),
r("english",0,["Vocabulary: Weather","Vocabulary","واژگان"],
"It's raining outside. Don't forget your ___!",
"It's raining outside. Don't forget your ___!",
"بیرون باران است؛ ___ ات را فراموش نکن: Don't forget your ___!",
["umbrella","sunscreen","sunglasses","swimsuit"],0,
"Yağmurda şemsiye (umbrella) gerekir ☔",
"When it rains you need an umbrella ☔",
"در باران چتر لازم است ☔"),
/* ── english · Altın ── */
r("english",1,["Present Perfect","Present Perfect","حال کامل"],
"I ___ lived in Kyrenia since 2019.","I ___ lived in Kyrenia since 2019.","از ۲۰۰۹...: I ___ lived in Kyrenia since 2019.",
["have","has","had","was"],0,
"'Since + yıl' → Present Perfect: I/you/we/they have …",
"'Since + year' → Present Perfect; with I it is 'have'.",
"با since زمان حال‌کامل و با I ضمیر have می‌آید."),
r("english",1,["Passive Voice","Passive Voice","مجعول"],
"The cake ___ by my grandmother yesterday.",
"The cake ___ by my grandmother yesterday.",
"کیک توسط مادر‌بزرگم پخته شد: The cake ___ by my grandmother.",
["made","was made","is made","makes"],1,
"Geçmiş pasif: was/were + V3 → was made.",
"Past passive: was/were + past participle → was made.",
"مجعول گذشته: was/were + اسم‌مفعول ← was made"),
r("english",1,["Future: going to","going to","آینده نزدیک"],
"Look at those black clouds! It ___ rain.",
"Look at those black clouds! It ___ rain.",
"به ابرهای سیاه نگاه کن! باران خواهد آمد: It ___ rain.",
["will maybe","is going to","rains","rain"],1,
"Kanıta dayalı tahminler için 'be going to' kullanılır.",
"Use 'be going to' for predictions based on evidence.",
"برای پیش‌بینی بر مبنای شاهد از be going to استفاده می‌شود."),
r("english",1,["much / many","Quantifiers","much/many"],
"How ___ students are there in your class?",
"How ___ students are there in your class?",
"در کلاست چند دانش‌آموز هست؟ How ___ students are there...",
["much","many","a lot","any"],1,
"Sayılabilen çoğul adlarla 'many' kullanılır (students ✓).",
"'Many' goes with countable plural nouns (students ✓).",
"با اسم‌های شمارش‌پذیر جمع از many استفاده می‌شود."),
r("english",1,["Academic Vocabulary","Academic Vocab","واژگان آکادمیک"],
"Scientists ___ experiments to test their ideas.",
"Scientists ___ experiments to test their ideas.",
"دانشمندان برای آزمودن ایده‌هایشان آزمایش ___: Scientists ___ experiments.",
["conduct","lead","build","take"],0,
"'Conduct an experiment' bilimsel bir kalıptır (experiment yapmak).",
"'Conduct an experiment' is the correct academic collocation.",
"عبارت علمی درست conduct an experiment است."),
/* ── english · Elmas ── */
r("english",2,["Conditionals","Conditionals","شرطی"],
"If I ___ rich, I would buy a sailing boat.",
"If I ___ rich, I would buy a sailing boat.",
"اگر ثروتمند بودم قایق می‌خریدم: If I ___ rich, I would buy...",
["am","was","were","be"],2,
"2. tip koşul cümlesinde (hayalî) 'were' kullanılır.",
"In the second conditional (imaginary) we use 'were'.",
"در شرطی نوع دوم (خیالی) were می‌آید."),
r("english",2,["Idioms","Idioms","اصطلاحات"],
"The exam was a piece of cake — in other words, it was ___.",
"The exam was a piece of cake — in other words, it was ___.",
"امتحان piece of cake بود یعنی ___: it was ___.",
["very difficult","very easy","very long","very sweet"],1,
"'A piece of cake' = çok kolay bir şey 😄",
"'A piece of cake' means very easy 😄",
"‏a piece of cake یعنی خیلی آسان 😄"),
r("english",2,["Relative Clauses","Relative Clauses","جمله موصولی"],
"The scientist ___ discovered the new species won a prize.",
"The scientist ___ discovered the new species won a prize.",
"دانشمندی که گونه تازه را کشف کرد جایزه برد: The scientist ___ discovered...",
["which","who","whose","whom"],1,
"Özne konumunda insan için 'who' kullanılır.",
"Use 'who' for people in subject position.",
"برای انسان در جایگاه فاعل who می‌آید."),
r("english",2,["Academic Vocabulary","Academic Vocab","واژگان آکادمیک"],
"'Approximate' is closest in meaning to ___.",
"'Approximate' is closest in meaning to ___.",
"نزدیک‌ترین معنی Approximate چیست؟",
["exact","fast","nearly correct","expensive"],2,
"Approximate ≈ yaklaşık olarak doğru / tahmini.",
"'Approximate' ≈ nearly correct, estimated.",
"‏Approximate یعنی تقریبی و نزدیک‌به‌درست."),
r("english",2,["Reported Speech","Reported Speech","نقل‌قول"],
"He said that he ___ tired.","He said that he ___ tired.","او گفت که خسته است: He said that he ___ tired.",
["is","was","has been","will be"],1,
"Nakil cümlesinde zaman bir adım geriye gider: is → was.",
"In reported speech tenses shift one step back: is → was.",
"در نقل‌قول زمان یک پله عقب می‌رود: is → was"),

/* ── 🏛️ history · Gümüş (Kıbrıs Türk Tarihi üniteleri) ── */
r("history",0,["Klasik Dönem","Classical Era","دوره کلاسیک"],
"Kıbrıs adasını 1571'de fetheden devlet hangisidir?",
"Which state conquered Cyprus in 1571?",
"چه دولتی در سال ۱۵۷۱ قبرس را فتح کرد؟",
["İngiltere","Osmanlı Devleti","Venedik","Bizans"],
["England","The Ottoman Empire","Venice","Byzantium"],
["انگلستان","امپراتوری عثمانی","ونیز","بیزانس"],1,
"1571'de Osmanlılar Venediklilerden adayı aldı; Kıbrıs 307 yıl Osmanlı yönetiminde kaldı.",
"The Ottomans took Cyprus from Venice in 1571; it stayed Ottoman for 307 years.",
"در ۱۵۷۱ عثمانی‌ها قبرس را از ونیز گرفتند و ۳۰۷ سال حکومت کردند."),
r("history",0,["1974","1974","۱۹۷۴"],
"1974'te gerçekleşen harekâtın adı nedir?","What is the name of the 1974 operation on the island?","نام عملیات سال ۱۹۷۴ در جزیره چیست؟",
["Barış Harekâtı","Yeşil Hat Operasyonu","Ada Seferi","Maraş Harekâtı"],
["Peace Operation (Barış Harekâtı)","Green Line Operation","Island Campaign","Maraş Operation"],
["عملیات صلح (Barış Harekâtı)","عملیات خط سبز","عملیات جزیره","عملیات مرعش"],0,
"20 Temmuz 1974 Barış Harekâtı — 8. sınıf müfredatının kilit olayıdır.",
"The 20 July 1974 Peace Operation is a key event in the grade-8 syllabus.",
"عملیات صلح ۲۰ جولای ۱۹۷۴ رویداد کلیدی سرفصل پایه ۸ است."),
r("history",0,["Cumhuriyet","The Republic","جمهوری"],
"Kıbrıs Cumhuriyeti hangi yıl kurulmuştur?","In which year was the Republic of Cyprus founded?","جمهوری قبرس در چه سالی بنیان شد؟",
["1945","1959","1960","1974"],2,
"1959 Zürih-Londra Anlaşmaları'nın ardından cumhuriyet 1960'ta ilan edildi.",
"After the 1959 Zurich-London agreements, the republic was declared in 1960.",
"پس از موافقت‌نامه‌های زوریخ-لندن ۱۹۵۹، جمهوری در ۱۹۶۰ اعلام شد."),
r("history",0,["KKTC","TRNC","KKTC"],
"KKTC hangi yıl ilan edilmiştir?","In which year was the TRNC (KKTC) proclaimed?","KKTC در چه سالی اعلام شد؟",
["1974","1975","1983","2004"],2,
"15 Kasım 1983'te Kuzey Kıbrıs Türk Cumhuriyeti ilan edildi.",
"The TRNC was proclaimed on 15 November 1983.",
"در ۱۵ نوامبر ۱۹۸۳ جمهوری ترک قبرس شمالی اعلام شد."),
r("history",0,["1945-1960","1945–1960","۱۹۴۵ تا ۱۹۶۰"],
"Kıbrıs Türklerinin bu dönemdeki direniş teşkilatının adı nedir?",
"What was the Turkish Cypriot resistance organisation of this era?",
"سازمان مقاومت ترک‌های قبرس در این دوره چه نام داشت؟",
["TMT (Türk Mukavemet Teşkilatı)","EOKA","NATO","Birleşmiş Milletler"],
["TMT (Turkish Resistance Organisation)","EOKA","NATO","United Nations"],
["ت‌م‌ت (سازمان مقاومت ترک)","EOKA","ناتو","سازمان ملل"],0,
"TMT 1958'de kuruldu; EOKA ise Rum tarafının örgütüdür.",
"TMT was founded in 1958; EOKA was the Greek Cypriot organisation.",
"سازمان ت‌م‌ت در ۱۹۵۸ بنیان شد؛ EOKA سازمان سمت روم بود."),
/* ── history · Altın ── */
r("history",1,["Anlaşmalar","Agreements","موافقت‌نامه‌ها"],
"1960 Garanti Antlaşmaları'na göre garantör devletler hangileridir?",
"Under the 1960 Treaties of Guarantee, which are the guarantor powers?",
"طبق پیمان‌های ضمانت ۱۹۶۰، دولت‌های ضامن کدام‌اند؟",
["Türkiye, Yunanistan, İngiltere","Türkiye, ABD, Rusya","İngiltere, Fransa, İtalya","Yunanistan, Mısır, Türkiye"],
["Turkey, Greece, United Kingdom","Turkey, USA, Russia","UK, France, Italy","Greece, Egypt, Turkey"],
["ترکیه، یونان، بریتانیا","ترکیه، آمریکا، روسیه","بریتانیا، فرانسه، ایتالیا","یونان، مصر، ترکیه"],0,
"Üç garantör: Türkiye, Yunanistan ve İngiltere.",
"The three guarantors: Turkey, Greece and the United Kingdom.",
"سه ضامن: ترکیه، یونان و بریتانیا."),
r("history",1,["1975","1975","۱۹۷۵"],
"1975'te KKTC'den önce kurulan devletin adı nedir?",
"Which state was formed in 1975, before the TRNC?",
"در ۱۹۷۵ و پیش از KKTC چه دولتی تشکیل شد؟",
["Kıbrıs Türk Federe Devleti (KTFD)","Geçici Kıbrıs Türk Yönetimi (1967)","Kıbrıs Cumhuriyeti","Otonom Türk Yönetimi"],
["Turkish Federated State of Cyprus","Provisional Turkish Cypriot Administration (1967)","Republic of Cyprus","Autonomous Turkish Administration"],
["دولت فدرال ترک قبرس","اداره موقت ترک قبرس (۱۹۶۷)","جمهوری قبرس","اداره خودگردان ترک"],0,
"Geçici Yönetim (1967) → KTFD (1975) → KKTC (1983).",
"Provisional Administration (1967) → Federated State (1975) → TRNC (1983).",
"اداره موقت (۱۹۶۷) ← دولت فدرال (۱۹۷۵) ← KKTC (۱۹۸۳)."),
r("history",1,["İnkılap Tarihi","Turkish History","تاریخ انقلاب"],
"'Ya İstiklal Ya Ölüm' parolası hangi döneme aittir?",
"To which era does the motto 'Independence or Death' belong?",
"شعار «یا استقلال یا مرگ» به کدام دوره تعلق دارد؟",
["Milli Mücadele Dönemi","I. Dünya Savaşı","Trablusgarp Savaşı","Tanzimat Dönemi"],
["The National Struggle (War of Independence)","World War I","Tripolitanian War","Tanzimat era"],
["دوره مبارزه ملی","جنگ جهانی اول","جنگ طرابلس","دوره تنظیمات"],0,
"Bu parola, 3. ünitedeki Milli Mücadele (Kurtuluş Savaşı) döneminin simgesidir.",
"This motto symbolises the War of Independence era (syllabus unit 3).",
"این شعار نماد دوره مبارزه ملی (واحد ۳ سرفصل) است."),
r("history",1,["Kavramlar","Concepts","مفاهیم"],
"'Enosis' kavramı neyi ifade eder?",
"What does 'Enosis' mean?",
"«Enosis» به چه معناست؟",
["Adanın Yunanistan'a bağlanması hedefi","Adanın tam bağımsızlığı","Adanın ikiye bölünmesi (Taksim)","Ada'da federasyon kurulması"],
["The goal of uniting the island with Greece","Full independence of the island","Partition of the island (Taksim)","Setting up a federation"],
["هدف پیوستن جزیره به یونان","استقلال کامل جزیره","تقسیم جزیره (Taksim)","تشکیل فدراسیون"],0,
"Enosis, EOKA'nın hedefiydi; Taksim ise adanın iki toplumlu bölünme fikridir.",
"Enosis was EOKA's goal; Taksim is the partition concept.",
"«Enosis» هدف EOKA بود؛ Taksim یعنی تقسیم جزیره."),
r("history",1,["İnkılap Tarihi","Turkish History","تاریخ انقلاب"],
"Türkiye Cumhuriyeti'nin ilanı hangi yıldır?",
"In which year was the Republic of Türkiye proclaimed?",
"جمهوری ترکیه در چه سالی اعلام شد؟",
["1920","1922","1923","1938"],2,
"29 Ekim 1923 — Cumhuriyet'in ilanı.",
"29 October 1923 — the proclamation of the Republic.",
"٢٩ اکتبر ۱۹۲۳ — اعلام جمهوری."),
/* ── history · Elmas ── */
r("history",2,["Anlaşmalar","Agreements","موافقت‌نامه‌ها"],
"Kıbrıs Cumhuriyeti'ni doğuran 1959 anlaşmaları hangi şehirlerde imzalandı?",
"The 1959 agreements that created the Republic of Cyprus were signed in which cities?",
"موافقت‌نامه‌های ۱۹۵۹ که جمهوری قبرس را ساختند در کدام شهرها امضا شد؟",
["Zürih ve Londra","Paris ve Roma","Cenevre ve Lozan","Atina ve İstanbul"],
["Zurich and London","Paris and Rome","Geneva and Lausanne","Athens and Istanbul"],
["زوریخ و لندن","پاریس و رم","ژنو و لوزان","آتن و استانبول"],0,
"Zürih'te temel metin, Londra'da resmî imzalar atıldı (Şubat 1959).",
"Drafted in Zurich, formally signed in London (February 1959).",
"متن در زوریخ و امضای رسمی در لندن (ژانویه-فوریه ۱۹۵۹)."),
r("history",2,["1963-1967","1963–1967","۱۹۶۳ تا ۱۹۶۷"],
"1963 sonrası dönem ortaklık cumhuriyeti için nasıl adlandırılır?",
"How is the period after 1963 described for the partnership republic?",
"دوره پس از ۱۹۶۳ برای جمهوری مشترک چگونه نامیده می‌شود؟",
["Sorunlu yıllar (Kanlı Noel ile ayrışma)","Altın yıllar","Barış yılları","Federe yıllar"],
["The troubled years (split after 'Bloody Christmas')","The golden years","The years of peace","The federated years"],
["سال‌های پرتلاطم (جدایی پس از «کریسمس خونین»)","سال‌های طلایی","سال‌های صلح","سال‌های فدرال"],0,
"Aralık 1963 olayları sonrası iki toplum ayrıştı — müfredatta 'sorunlu yıllar'.",
"After December 1963 the two communities split — the syllabus calls them the troubled years.",
"پس از دسامبر ۱۹۶۳ دو جامعه از هم جدا شدند — سرفصل: سال‌های پرتلاطم."),
r("history",2,["Kronoloji","Chronology","گاه‌نگاری"],
"Geçici Kıbrıs Türk Yönetimi hangi yılda kurulmuştur?",
"In which year was the Provisional Turkish Cypriot Administration set up?",
"اداره موقت ترک قبرس در چه سالی تأسیس شد؟",
["1960","1967","1974","1983"],1,
"1967 Geçici Yönetim → 1971 Otonom statü → 1975 KTFD.",
"1967 Provisional Administration → 1975 Federated State.",
"۱۹۶۷ اداره موقت ← ۱۹۷۵ دولت فدرال."),
r("history",2,["Uluslararası","International","بین‌المللی"],
"KKTC'yi resmen tanıyan BM üyesi devlet hangisidir?",
"Which UN member state officially recognises the TRNC?",
"کدام عضو سازمان ملل KKTC را رسماً به رسمیت می‌شناسد؟",
["Yunanistan","İngiltere","Türkiye","Amerika Birleşik Devletleri"],
["Greece","United Kingdom","Türkiye","United States"],
["یونان","بریتانیا","ترکیه","ایالات متحده"],2,
"KKTC'yi tanıyan tek BM üyesi devlet Türkiye'dir.",
"Türkiye is the only UN member recognising the TRNC.",
"تنها عضو سازمان ملل که KKTC را می‌شناسد ترکیه است."),
r("history",2,["Genel Bilgi","General","عمومی"],
"Kıbrıs, Akdeniz'in en büyük kaçıncı adasıdır?",
"Cyprus is the ___ largest island in the Mediterranean.",
"قبرس چندمین جزیره بزرگ مدیترانه است؟",
["Birinci / First / اول","İkinci / Second / دوم","Üçüncü / Third / سوم","Beşinci / Fifth / پنجم"],2,
"Sicilya ve Sardinya'dan sonra üçüncüdür.",
"It comes third after Sicily and Sardinia.",
"پس از سیسیل و ساردنی سومین جزیره است."),

/* ── 🗺️ geo · Gümüş ── */
r("geo",0,["Şehirler","Cities","شهرها"],
"KKTC'nin başkenti ve en kalabalık şehri hangisidir?",
"What is the capital and most populous city of North Cyprus?",
"پایتخت و پرجمعیت‌ترین شهر قبرس شمالی کدام است؟",
["Girne","Gazimağusa","Lefkoşa","Güzelyurt"],
["Kyrenia","Famagusta","Nicosia (Lefkoşa)","Güzelyurt"],
["گیرنه","غازی‌مغوسا","لفکوشا","گوزل‌یورت"],2,
"Lefkoşa (Nicosia) başkenttir ve adanın tam ortasında yer alır.",
"Nicosia (Lefkoşa) is the capital, right in the middle of the island.",
"لفکوشا (نیکوزیا) پایتخت در مرکز جزیره است."),
r("geo",0,["Yer Şekilleri","Landforms","چهره‌های زمین"],
"Kuzey kıyı boyunca uzanan sıradağların adı nedir?",
"What is the mountain range along the northern coast called?",
"رشته‌کوه امتداد ساحل شمالی چه نام دارد؟",
["Beşparmak (Girne) Dağları","Toros Dağları","Trodos Dağları","Kaçkar Dağları"],
["The Kyrenia (Beşparmak) Mountains","The Taurus Mountains","The Troodos Mountains","The Kaçkar Mountains"],
["کوه‌های پنج‌پر (گیرنه)","کوه‌های طوروس","کوه‌های ترودوس","کوه‌های قاچقار"],0,
"Beşparmak Dağları kuzey kıyıya paralel uzanır; Trodos ise güneydedir.",
"The Kyrenia (Beşparmak) range runs parallel to the north coast; Troodos is in the south.",
"رشته‌کوه پنج‌پر (گیرنه) موازی ساحل شمالی است؛ ترودوس در جنوب."),
r("geo",0,["Tarım","Agriculture","کشاورزی"],
"Kıbrıs'ın en verimli tahıl ve patates ovası hangisidir?",
"What is the island's most fertile plain for grain and potatoes?",
"حاصلخیزترین دشت جزیره برای گندم و سیب‌زمینی کدام است؟",
["Mesarya Ovası","Çukurova","Harran Ovası","Karpaz Vadisi"],
["Mesarya (Mesaoria) Plain","Çukurova","Harran Plain","Karpaz Valley"],
["دشت مساریا","چوکورووا","دشت حران","دره کارپاس"],0,
"Mesarya Ovası, Lefkoşa-Gazimağusa arasında geniş bir tarım havzasıdır.",
"The Mesaoria plain between Nicosia and Famagusta is the farming heartland.",
"دشت مساریا میان لفکوشا و غازی‌مغوسا قلب کشاورزی است."),
r("geo",0,["İklim","Climate","اقلیم"],
"Kuzey Kıbrıs hangi iklim kuşağındadır?",
"In which climate zone is North Cyprus?",
"قبرس شمالی در کدام کمربند اقلیمی است؟",
["Karasal iklim","Akdeniz iklimi","Tropikal iklim","Kutup iklimi"],
["Continental","Mediterranean","Tropical","Polar"],
["قاره‌ای","مدیترانه‌ای","گرمسیری","قطبی"],1,
"Yazları sıcak-kurak, kışları ılık-yağışlı: klasik Akdeniz iklimi.",
"Hot dry summers, mild rainy winters: classic Mediterranean climate.",
"تابستان گرم و خشک، زمستان معتدل و بارانی: اقلیم مدیترانه‌ای."),
r("geo",0,["Konum","Location","موقعیت"],
"Kuzey Kıbrıs'ın deniz yoluyla en yakın olduğu kuzeydeki ülke hangisidir?",
"Which country lies nearest to the north of North Cyprus by sea?",
"کدام کشور در شمال قبرس شمالی از راه دریا نزدیک‌ترین است؟",
["Mısır","Suriye","Yunanistan","Türkiye"],
["Egypt","Syria","Greece","Türkiye"],
["مصر","سوریه","یونان","ترکیه"],3,
"Adanın kuzeyinde ~70 km mesafede Türkiye kıyıları vardır.",
"Turkey's coast lies about 70 km north of the island.",
"ساحل ترکیه در حدود ۷۰ کیلومتری شمال جزیره است."),
/* ── geo · Altın ── */
r("geo",1,["Ekonomi","Economy","اقتصاد"],
"Güzelyurt bölgesi hangi tarım ürünüyle ünlüdür?",
"Which crop is the Güzelyurt region famous for?",
"ناحیه گوزل‌یورت به کدام محصول مشهور است؟",
["Zeytin","Narenciye (portakal)","Üzüm","Fındık"],
["Olives","Citrus (oranges)","Grapes","Hazelnuts"],
["زیتون","مرکبات (پرتقال)","انگور","فندق"],1,
"Güzelyurt = portakal bahçeleri; her yaz Portakal Festivali yapılır! 🍊",
"Güzelyurt means orange orchards — it hosts the Orange Festival! 🍊",
"گوزل‌یورت یعنی باغ‌های پرتقال و جشنواره پرتقال! 🍊"),
r("geo",1,["Su Kaynakları","Water Resources","منابع آب"],
"KKTC'nin içme suyunun önemli bölümü hangi projeyle karşılanır?",
"Which project supplies much of the TRNC's drinking water?",
"بخش مهم آب آشامیدنی KKTC با کدام پروژه تأمین می‌شود؟",
["Türkiye'den deniz altı boru hattı","Sadece yağmur suyu","Sadece kuyular","Sadece tuzdan arındırma"],
["An undersea pipeline from Türkiye","Only rainwater","Only wells","Only desalination"],
["خط لوله زیردریایی از ترکیه","فقط آب باران","فقط چاه","فقط شیرین‌سازی"],0,
"'Asrın Projesi' (2015) denizin altından adaya tatlı su taşır.",
"The 'Project of the Century' (2015) carries fresh water under the sea to the island.",
"پروژه خط لوله زیر دریا (۲۰۱۵) آب شیرین به جزیره می‌رساند."),
r("geo",1,["Sektörler","Sectors","بخش‌ها"],
"KKTC'nin 'yükseköğrenim adası' olarak anılmasını sağlayan sektör hangisidir?",
"Which sector makes North Cyprus an 'island of higher education'?","کدام بخش قبرس شمالی را «جزیره آموزش عالی» کرده است؟",
["Madencilik","Üniversiteler","Balıkçılık","Ormancılık"],
["Mining","Universities","Fishing","Forestry"],
["معدن","دانشگاه‌ها","ماهیگیری","جنگل‌داری"],1,
"Adada çok sayıda uluslararası üniversite ve 100+ ülkeden öğrenci vardır.",
"The island hosts many international universities with students from 100+ countries.",
"در جزیره دانشگاه‌های بین‌المللی بسیار و دانشجو از ۱۰۰+ کشور است."),
r("geo",1,["Turizm","Tourism","گردشگری"],
"Kalesi ve marinasıyla ünlü turizm şehri hangisidir?",
"Which tourism city is famous for its castle and marina?",
"کدام شهر توریستی به قلعه و مارینا معروف است؟",
["Lefke","İskele","Girne","Lefkoşa"],
["Lefke","İskele","Kyrenia (Girne)","Nicosia"],
["لفکه","اسکله","گیرنه","لفکوشا"],2,
"Girne Kalesi ve eski limanı, adanın en çok fotoğraflanan yerlerindendir. 📸",
"Kyrenia Castle and the old harbour are the island's most photographed spots. 📸",
"قلعه و بندر قدیمی گیرنه بیشترین عکس‌های جزیره را دارد. 📸"),
r("geo",1,["Turizm","Tourism","گردشگری"],
"Adada turizmin en yoğun olduğu dönem ve tür hangisidir?",
"What is the island's peak tourism season and type?",
"شلوغ‌ترین فصل و نوع گردشگری جزیره چیست؟",
["Yaz — deniz turizmi","Kış — kayak turizmi","Sonbahar — av turizmi","Sadece kongre turizmi"],
["Summer — beach tourism","Winter — ski tourism","Autumn — hunting tourism","Only congress tourism"],
["تابستان — گردشگری ساحل","زمستان — اسکی","پاییز — شکار","فقط کنگره"],0,
"Akdeniz iklimi → yaz aylarında sahiller ve oteller dolup taşar.",
"Mediterranean climate → beaches and hotels fill up in summer.",
"اقلیم مدیترانه‌ای ← تابستان ساحل‌ها شلوغ می‌شود."),
/* ── geo · Elmas ── */
r("geo",2,["Koordinatlar","Coordinates","مختصات"],
"Kıbrıs'ın coğrafi konumu yaklaşık hangisidir?",
"What are the approximate coordinates of Cyprus?",
"مختصات تقریبی قبرس کدام است؟",
["35° K, 33° D","45° K, 15° D","25° K, 45° D","55° K, 33° D"],
["35° N, 33° E","45° N, 15° E","25° N, 45° E","55° N, 33° E"],
["۳۵° شمالی، ۳۳° شرقی","۴۵° شمالی، ۱۵° شرقی","۲۵° شمالی، ۴۵° شرقی","۵۵° شمالی، ۳۳° شرقی"],0,
"Kıbrıs ~35° kuzey enlemi, ~33° doğu boylamındadır.",
"Cyprus lies at about 35° N latitude and 33° E longitude.",
"قبرس در حدود ۳۵ درجه شمالی و ۳۳ درجه شرقی است."),
r("geo",2,["Su Yönetimi","Water Management","مدیریت آب"],
"Kurak Akdeniz ikliminde tarımda en verimli sulama yöntemi hangisidir?",
"What is the most efficient irrigation method for a dry Mediterranean climate?",
"کارآمدترین روش آبیاری در اقلیم خشک مدیترانه‌ای کدام است؟",
["Salma sulama (tarlayı su basma)","Damlama sulama","Sürekli yağmurlama","Sulamaya gerek yok"],
["Flood irrigation","Drip irrigation","Constant sprinklers","No irrigation needed"],
["غرق‌آبیاری","آبیاری قطره‌ای","آب‌پاشی دائم","بی‌نیازی از آبیاری"],1,
"Damlama sulama suyu doğrudan köke ulaştırır — %60'a kadar tasarruf.",
"Drip irrigation delivers water straight to roots — saves up to 60%.",
"آبیاری قطره‌ای آب را به ریشه می‌رساند — تا ۶۰٪ صرفه‌جویی."),
r("geo",2,["Doğal Yaşam","Wildlife","حیات وحش"],
"Karpaz Yarımadası'nın doğal yaşam simgesi hangisidir?",
"What is the wildlife icon of the Karpaz Peninsula?",
"نماد حیات‌وحش شبه‌جزیره کارپاس چیست؟",
["Yabani eşekler","Kangurular","Kutup ayıları","Develer"],
["Wild donkeys","Kangaroos","Polar bears","Camels"],
["الاغ‌های وحشی","کانگورو","خرس قطبی","شتر"],0,
"Karpaz'ın özgür dolaşan yabani eşekleri ulusal parkta korunur. 🫏",
"The free-roaming wild donkeys of Karpaz live in the national park. 🫏",
"الاغ‌های وحشی آزاد کارپاس در پارک ملی محافظت می‌شوند. 🫏"),
r("geo",2,["Enerji","Energy","انرژی"],
"Kuzey Kıbrıs'ta en yüksek potansiyelli yenilenebilir enerji kaynağı hangisidir?",
"Which renewable energy source has the highest potential in North Cyprus?",
"پرپتانسیل‌ترین انرژی تجدیدپذیر در قبرس شمالی کدام است؟",
["Rüzgâr enerjisi","Güneş enerjisi","Jeotermal","Dalga enerjisi"],
["Wind power","Solar power","Geothermal","Wave power"],
["بادی","خورشیدی","زمین‌گرمایی","موج"],1,
"Yılda 300+ gün güneşli hava → güneş enerjisi devasa potansiyel. ☀️",
"300+ sunny days a year → huge solar potential. ☀️",
"بیش از ۳۰۰ روز آفتابی در سال ← پتانسیل عظیم خورشیدی. ☀️"),
r("geo",2,["Çevre","Environment","محیط زیست"],
"Kıyı şeridinde hızlı yapılaşmanın başlıca çevresel riski nedir?",
"What is the main environmental risk of rapid coastal construction?",
"خطر اصلی زیست‌محیطی ساخت‌وساز سریع در نوار ساحلی چیست؟",
["Kıyı ekosistemleri ve kaplumbağa yuvalarının zarar görmesi","Kar yağışının artması","Ekin veriminin artması","Nüfusun azalması"],
["Damage to coastal ecosystems and turtle nesting beaches","More snowfall","Higher crop yields","Population decline"],
["آسیب به اکوسیستم ساحل و پناهگاه لاک‌پشت‌ها","برف بیشتر","محصول بیشتر","کاهش جمعیت"],0,
"Caretta caretta kaplumbağalarının yuvalama plajları kıyı baskısı altındadır. 🐢",
"Loggerhead turtle nesting beaches are under coastal pressure. 🐢",
"ساحل‌های لانه‌سازی لاک‌پشت‌ها زیر فشار است. 🐢"),

/* ── 🧩 zeka · Gümüş (Zekâ Oyunları müfredatı) ── */
r("zeka",0,["Örüntü","Patterns","الگو"],
"Örüntüyü tamamla: 2, 4, 8, 16, ?",
"Complete the pattern: 2, 4, 8, 16, ?","الگو را کامل کن: ۲،۴،۸،۱۶، ؟",
["24","32","20","18"],1,
"Her adımda sayı 2 ile çarpılıyor: 16 × 2 = 32",
"Each step doubles the number: 16 × 2 = 32",
"هر قدم عدد دو برابر می‌شود: ۱۶ × ۲ = ۳۲"),
r("zeka",0,["Sayı Bulmaca","Number Puzzle","معمای عددی"],
"3 keçi ve 2 tavuğun toplam ayak sayısı kaçtır?",
"What is the total number of legs of 3 goats and 2 chickens?",
"۳ بز و ۲ مرغ روی هم چند پا دارند؟",
["10","12","16","20"],2,
"3×4 + 2×2 = 12 + 4 = 16 ayak 🐐🐔","3×4 + 2×2 = 16 legs 🐐🐔","‏۳×۴ + ۲×۲ = ۱۶ پا 🐐🐔"),
r("zeka",0,["Ayıklama","Odd One Out","تفkig زدن"],
"Hangisi diğerlerinden FARKLIDIR?","Which one is the ODD one out?","کدام‌یک با بقیه فرق دارد؟",
["Elma","Armut","Havuç","Muz"],
["Apple","Pear","Carrot","Banana"],
["سیب","گلابی","هویج","موز"],2,
"Havuç sebze, diğerleri meyvedir. 🥕","The carrot is a vegetable; the rest are fruits. 🥕","هویج سبزی است و بقیه میوه‌اند. 🥕"),
r("zeka",0,["Yansıma","Mirror Image","آینه"],
"Saat 03:00'ı aynaya tutarsan kaç görünür?",
"If you hold 03:00 up to a mirror, what time appears?",
"اگر ساعت ۰۳:۰۰ را جلوی آینه بگیری چند دیده می‌شود؟",
["03:00","09:00","06:00","12:00"],1,
"Ayna sağ-sol değiştirir: 3 ↔ 9.","A mirror flips left and right: 3 ↔ 9.","آینه چپ‌وراست را عوض می‌کند: ۳ ↔ ۹"),
r("zeka",0,["Zihin Hesabı","Mental Math","حساب ذهنی"],
"Otobüste 10 yolcu var; durakta 3 iner, 5 biner. Kaç yolcu kalır?",
"A bus carries 10 passengers; 3 get off and 5 get on. How many remain?",
"در اتوبوس ۱۰ نفرند؛ ۳ پیاده و ۵ سوار می‌شوند. چند نفر می‌مانند؟",
["8","12","15","18"],1,
"10 − 3 + 5 = 12 🚌","10 − 3 + 5 = 12 🚌","‏۱۰ − ۳ + ۵ = ۱۲ 🚌"),
/* ── zeka · Altın ── */
r("zeka",1,["Diziler","Sequences","دنباله‌ها"],
"Fibonacci dizisini tamamla: 1, 1, 2, 3, 5, 8, ?",
"Complete the Fibonacci sequence: 1, 1, 2, 3, 5, 8, ?","دنباله فیبوناچی: ۱،۱،۲،۳،۵،۸، ؟",
["11","12","13","15"],2,
"Her terim önceki ikisinin toplamı: 5 + 8 = 13",
"Each term is the sum of the previous two: 5 + 8 = 13",
"هر جمله جمع دو جمله قبلی است: ۸ + ۵ = ۱۳"),
r("zeka",1,["Diziler","Sequences","دنباله‌ها"],
"Kuralı bul: 5, 11, 23, 47, ? (ipucu: ×2 + 1)",
"Find the rule: 5, 11, 23, 47, ? (hint: ×2 + 1)","قاعده را بیاب: ۵،۱۱،۲۳،۴۷، ؟ (راهنما: ×۲ + ۱)",
["71","95","94","99"],1,
"47 × 2 + 1 = 95","47 × 2 + 1 = 95","‏۴۷ × ۲ + ۱ = ۹۵"),
r("zeka",1,["Kare Sayılar","Square Numbers","اعداد مربع"],
"Kare sayılar dizisi: 1, 4, 9, 16, 25, 36, ?",
"Square numbers: 1, 4, 9, 16, 25, 36, ?","اعداد مربع: ۱،۴،۹،۱۶،۲۵،۳۶، ؟",
["42","49","45","48"],1,
"1×1, 2×2, … 7×7 = 49","1², 2², … 7² = 49","‏۱² تا ۷² ← ۷² = ۴۹"),
r("zeka",1,["Mantık","Logic","منطق"],
"Ali, Veli'den uzun boylu; Veli de Zeynep'ten uzun. En kısa kimdir?",
"Ali is taller than Veli; Veli is taller than Zeynep. Who is the shortest?",
"علی از ولی قدبلندتر است و ولی از زینب. کوتاه‌ترین کیست؟",
["Ali","Veli","Zeynep","Belli değil / Cannot tell / مشخص نیست"],2,
"Ali > Veli > Zeynep → en kısa Zeynep.","Ali > Veli > Zeynep, so Zeynep is shortest.","علی > ولی > زینب ← کوتاه‌ترین زینب است."),
r("zeka",1,["Zihin Hesabı","Mental Math","حساب ذهنی"],
"Bir çiftçinin 17 koyunu vardı, 9'unu sattı. Kaç koyunu kaldı?",
"A farmer had 17 sheep and sold 9. How many are left?","کشاورزی ۱۷ گوسفند داشت، ۹ تا را فروخت. چند تا ماند؟",
["7","8","9","26"],1,
"17 − 9 = 8 🐑","17 − 9 = 8 🐑","‏۱۷ − ۹ = ۸ 🐑"),
/* ── zeka · Elmas ── */
r("zeka",2,["Asal Sayılar","Primes","اعداد اول"],
"Asal sayı dizisi: 2, 3, 5, 7, 11, 13, ?",
"Prime numbers: 2, 3, 5, 7, 11, 13, ?","اعداد اول: ۲،۳،۵،۷،۱۱،۱۳، ؟",
["15","16","17","19"],2,
"13'ten sonraki asal sayı 17'dir (14, 15, 16 asal değildir).",
"The next prime after 13 is 17 (14, 15 and 16 are not prime).",
"عدد اول بعد از ۱۳، عدد ۱۷ است."),
r("zeka",2,["Fonksiyon Dizisi","Function Sequence","دنباله تابعی"],
"f(n) = 3n − 1 dizisi: 2, 5, 8, 11, ?",
"The sequence f(n) = 3n − 1 gives: 2, 5, 8, 11, ?",
"‏f(n) = 3n − 1: ۲،۵،۸،۱۱، ؟",
["13","14","15","17"],1,
"Her adımda 3 ekleniyor: 11 + 3 = 14",
"Each step adds 3: 11 + 3 = 14",
"هر قدم ۳ اضافه می‌شود: ۱۱ + ۳ = ۱۴"),
r("zeka",2,["Olana Sayısı","Counting","شمارش"],
"4 farklı renk arasından 2 renk seçmenin kaç yolu vardır?",
"In how many ways can you pick 2 colours out of 4?",
"از ۴ رنگ متفاوت، ۲ رنگ به چند طریق انتخاب می‌شود؟",
["4","6","8","12"],1,
"C(4,2) = 6 farklı çift 🎨","C(4,2) = 6 different pairs 🎨","‏C(4,2) = ۶ جفت متفاوت 🎨"),
r("zeka",2,["Klasik Mantık","Classic Logic","منطق کلاسیک"],
"Koşu yarışında ikinci olan koşucuyu geçersen kaçıncı olursun?",
"In a race, if you pass the runner in 2nd place, what place are you in?",
"اگر در مسابقه نفر دوم را پشت سر بگذاری چندم می‌شوی؟",
["Birinci / 1st / اول","İkinci / 2nd / دوم","Üçüncü / 3rd / سوم","Sonuncu / Last / آخر"],1,
"İkinciyi geçince onun yerini alırsın → 2. olursun. (1. olmak için birinciyi geçmek gerekirdi)",
"Passing the 2nd runner takes their place → you are 2nd now.",
"با سبقت از نفر دوم، جای او را می‌گیری ← دوم می‌شوی."),
r("zeka",2,["Saat Bulmaca","Clock Puzzle","معمای ساعت"],
"12 saatlik sürede akrep ile yelkovan kaç kez üst üste gelir?",
"In 12 hours, how many times do the hour and minute hands overlap?",
"در ۱۲ ساعت، عقربه‌های ساعت و دقیقه چند بار روی هم می‌افتند؟",
["12","11","10","24"],1,
"Saatte 1 kez sanılanın aksine 12 saatte 11 kez çakışırlar. 🕐","They overlap 11 times in 12 hours — not 12! 🕐","در ۱۲ ساعت، ۱۱ بار روی هم می‌افتند نه ۱۲ بار! 🕐")
];


